version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/brain"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - dependencies
      - pip
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "/tests"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - dependencies
      - pip
    open-pull-requests-limit: 5
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - dependencies
      - ci
    open-pull-requests-limit: 5
